language: python

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - coverage run -m unittest discover
after_success:
  - codecov # submit coverage
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)